### ISSUE TITLE
GSoC Guidance 

### ISSUE THREAD

**Issue by fomalhauting** [uc3m-aerospace/MOLTO-3BP#6]
Hey, I would like to be a part of this project for GSoC 2021, I tried emailing people too, but could someone please guide me about the same? And how should I get started?

Thank you!

**Comment by fomalhauting** [comment]
@mariomerinomartinez @msanrivo @amogh-gulati @dmoranteg  Could someone help me, please?

**Comment by msanrivo** [comment]
Dear Kriti, 

the ideas on how to contribute to the project can be found in the organization website: 
((https://aerospaceresearch.net/?page_id=2156))

Best

**Comment by fomalhauting** [comment]
> Dear Kriti,
> 
> the ideas on how to contribute to the project can be found in the organization website:
> ((https://aerospaceresearch.net/?page_id=2156))
> 
> Best

Thank you, I went through that, I wanted to know if I should make a pull request before submitting my application?

**Comment by msanrivo** [comment]
No need to make a pull request. Better to see the functionalities of the cade and be familiar with it.

**Comment by fomalhauting** [comment]
Okay!! Great thanks a lot!

**Comment by itsIapetus** [comment]
Also extremely sorry but where else can I contact the potential mentors regarding my doubts?
